"""Agregar campo client_secret a tabla clients

Revision ID: 947a78b0ecc1
Revises: a5712eac2e5a
Create Date: 2025-08-27 21:40:05.554960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '947a78b0ecc1'
down_revision: Union[str, None] = 'a5712eac2e5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
