"""Agregar tabla ids_warehouse para almacenamiento de imágenes

Revision ID: a5712eac2e5a
Revises: 
Create Date: 2025-08-27 19:48:55.029733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5712eac2e5a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ids_warehouse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('credential_side', sa.Enum('FRONT', 'BACK', name='credentialside'), nullable=False),
    sa.Column('document_type', sa.Integer(), nullable=False),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.Column('is_rejected', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ids_warehouse_filename'), 'ids_warehouse', ['filename'], unique=False)
    op.create_index(op.f('ix_ids_warehouse_id'), 'ids_warehouse', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ids_warehouse_id'), table_name='ids_warehouse')
    op.drop_index(op.f('ix_ids_warehouse_filename'), table_name='ids_warehouse')
    op.drop_table('ids_warehouse')
    # ### end Alembic commands ###
